spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306
    username: root
    password: 1234

server:
  port: 5100

logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] [%-5level] [%thread] %logger{15} - %msg%n"
  level:
    sql: debug

scheduler:
  properties:
    kakao-work-api-key: "6d1adfe5.44b854138bbe465d81129fd5d3749392"
  api-url: "https://api.kakaowork.com/v1/"
